on: [pull_request]

jobs:
  go-linus:
    runs-on: ubuntu-latest
    name: linus pull request review
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Review PR
      id: linus_review
      uses: ./
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{github.repository}}
          owner: ${{github.repository_owner}}
          prNumber: ${{github.event.number}}

    - name : get output
      run: echo "PR message is ${{ steps.linus_review.outputs.review}}"
