on: [pull_request]

jobs:
  go-linus:
    runs-on: ubuntu-latest
    name: linus pull request review
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Review PR
      id: linus_review
      uses: ./
    - name : get output
      run: echo "PR message is ${{ steps.linus_review.outputs.review}}"
