on: [push]

jobs:
  go-linus:
    runs-on: ubuntu-latest
    name: linus pull request review
    steps:
    - name: Review PR
      id: hello
      uses: ./
      with:
        who-to-greet: 'Linus'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"